#!/bin/bash

#  Copyright (c) 2010 Eric Bodden.
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License v1.0
#  which accompanies this distribution, and is available at
#  http://www.eclipse.org/legal/epl-v10.html
#  
#  Contributors:
#      Eric Bodden - initial API and implementation

. ./settings

for SIZE in small default large huge
do
	for BM in `${JVM} -jar ${DACAPOJAR} -l`
	do
		OUTDIR=${DUMPDIR}/${BM}-${SIZE}

		mkdir -p ${OUTDIR}

		COMMAND="${JVM} -cp ${DACAPOJAR} -javaagent:poa.jar=${OUTDIR} Harness ${DACAPOOPTS1} $BM -s $SIZE"

		echo recording run for $BM $SIZE...
		echo $COMMAND > ${OUTDIR}/run.log 2>&1
		eval $COMMAND >> ${OUTDIR}/run.log 2>&1
	done
done
