#!/bin/bash

#  Copyright (c) 2010 Eric Bodden.
#  All rights reserved. This program and the accompanying materials
#  are made available under the terms of the Eclipse Public License v1.0
#  which accompanies this distribution, and is available at
#  http://www.eclipse.org/legal/epl-v10.html
#  
#  Contributors:
#      Eric Bodden - initial API and implementation

. ./settings

for SIZE in small default large huge
do
	for BM in `${JVM} -jar ${DACAPOJAR} -l`
	do
		INDIR=${SOOTOUTDIR}/${BM}-${SIZE}/		

		COMMAND="${JVM} -cp ${DACAPOJAR} -javaagent:pia.jar=${INDIR} Harness ${DACAPOOPTS2} $BM -s $SIZE"

		echo running $BM $SIZE  with classes from ${INDIR}...
		echo $COMMAND > ${INDIR}/run.log 2>&1
		eval $COMMAND >> ${INDIR}/run.log 2>&1
	done
done
