<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.bodden.tamiflex</groupId>
        <artifactId>tamiflex-parent</artifactId>
        <version>trunk</version>
    </parent>
    <artifactId>playin-agent</artifactId>
    <properties>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <finalName>pia-${project.version}</finalName>
        <resources>
            <resource>
                <directory>.</directory>
                <includes><include>pia.properties</include></includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-runtime-sources</id>
                        <phase>generate-sources</phase>
                        <goals><goal>add-source</goal></goals>
                        <configuration>
                            <sources><source>rtlib</source></sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>shade</goal></goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Main-Class>de.bodden.tamiflex.playin.Agent</Main-Class>
                                        <Premain-Class>de.bodden.tamiflex.playin.Agent</Premain-Class>
                                        <Can-Retransform-Classes>true</Can-Retransform-Classes>
                                        <Implementation-Version>${project.version}</Implementation-Version>
                                        <Boot-Class-Path>pia-${project.version}.jar pia.jar</Boot-Class-Path>
                                    </manifestEntries>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>de.bodden.tamiflex</groupId>
            <artifactId>normalizer</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
